###################
###   PROGRAMS  ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
#$menu = rofi -show combi -combi-modes drun,calc -modes combi,calc
$textedit = code
