-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- require("~/.config/hypr/myColors.lua")

require("~/.config/hypr/config/monitors.lua")       -- Configures monitor layout and resolution
require("~/.config/hypr/config/programs.lua")       -- General variables affecting the system
require("~/.config/hypr/config/autostart.lua")      -- Defines application to launch on startup
require("~/.config/hypr/config/environment.lua")    -- Sets environment variables ans system behavior
require("~/.config/hypr/config/animations.lua")     -- Control window animations
require("~/.config/hypr/config/decoration.lua")     -- Controls visuals settings like themes and wallpapers
require("~/.config/hypr/config/input.lua")          -- Specifies input device rules
require("~/.config/hypr/config/binds.lua")          -- Defines custom keybindings
require("~/.config/hypr/config/window-rules.lua")   -- Window-specific rules for behavior and appearance
require("~/.config/hypr/config/permissions.lua")    -- Control permissions
require("~/.config/hypr/config/layout.lua")         --
require("~/.config/hypr/config/misc.lua")           --

hl.config({
    locale = pt_BR.utf-8
})

-- More info: https://wiki.hypr.land/
